### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Ravada** [mediabots/Linux-to-Windows-with-QEMU#4]
Sorry! None of Windows OS image urls are available , please report about this issue on Github page

**Comment by mediabots** [comment]
Really Sorry for my late reply.

It should be fixed now, one of windows OS URL would work now

Thanks

**Comment by Ravada** [comment]
Still getting the same error.

**Comment by mediabots** [comment]
In that case, your Server/VPS IP might be blocking content from my URLs

here two of my URLs:

https://ia601506.us.archive.org/4/items/WS2012R2/WS2012R2.ISO
http://51.15.226.83/WS2012R2.ISO

you can test them, both are working fine

solution is, you can download from one of those Direct URLs and then upload on some other server and get the direct URL
then edit the script(.sh) file, and replace string http://51.15.226.83/WS2012R2.ISO with your own direct url
Line numbers are: 35 & 39

**Comment by Ravada** [comment]
Uploaded to my own server and still get the same error..

http://prntscr.com/o3g0gv

**Comment by mediabots** [comment]
At first , my I know which Linux Distro are you using and its version number? eg, Ubuntu 18.04

![Capture](https://user-images.githubusercontent.com/46617144/59823693-a1a12180-934c-11e9-9a01-93d6f5310b5a.PNG)

Got the issue, its not about my direct urls of Windows ISO or your URL is not responding.

Its about curl command(which is required) is not installed on your system.
And script suppose to install "curl" automatically,
But since the if & elif statement (Line no.17 & Line no. 24) didn't work, its ends up with out installing curl.

Now question is why your system returning error for line 17 & line 24?

because ,I tested the script yesterday on my ubuntu 18.04  VPS, and it is working perfectly.

Please state the Linux Distro you are using and its version number.
So I can dig further

Thanks

**Comment by Ravada** [comment]
This time it worked, but "Connection refused by computer" when trying to connect

**Comment by Ravada** [comment]
root@server:~# Could not access KVM kernel module: Operation not permitted
failed to initialize KVM: Operation not permitted

**Comment by mediabots** [comment]
Give screenshots,so I can see

As I already asked you,
please state the Linux Distro you are using and its version number. eg, Ubuntu 18.04
So, I can see whats the problem

If possible also state the VPS Provider you are using and its plan name

My script Script support Ubuntu (as mentioned in requirements)

looking forward

Thanks

**Comment by mediabots** [comment]
> 
> 
> root@server:~# Could not access KVM kernel module: Operation not permitted
> failed to initialize KVM: Operation not permitted

That means , your web hosting provider not allowing Virtualization facility. That's why you are seeing such KVM error

Contact your web hosting for the support

Regards

**Comment by myshang1** [comment]
Hello this is available?

**Comment by myshang1** [comment]
does it work in  VPS in OVH?
